# Generated by Django 5.1.3 on 2025-04-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion & Apparel', 'Fashion & Apparel'), (' Electronics', ' Electronics'), ('Home & Living', 'Home & Living'), ('Food & Beverages', 'Food & Beverages'), (' Beauty & Personal Care', ' Beauty & Personal Care'), ('Toys, Kids & Baby', 'Toys, Kids & Baby'), ('Tools & Hardware', 'Tools & Hardware'), ('Automotive', 'Automotive'), (' Sports & Outdoors', ' Sports & Outdoors'), (' Gaming', ' Gaming'), ('Books & Stationery', 'Books & Stationery')], default='Home & Living', max_length=40),
        ),
    ]
